version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  webpacker:
    build: .
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - tmp:/usr/src/app/tmp
    ports:
      - '3035:3035'
  web:
    build: .
    command:
      - rails
      - server
      - -b
      - 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    depends_on:
      - db
      - webpacker
volumes:
  node_modules:
  tmp:
